ci: adds tag.yml
AllenNeuralDynamics/aind-data-asset-view pull request #34
Opened 2022-11-15 20:00 UTC by dana-rocha

2022-11-17 21:14 UTC, dana-rocha commented
Closes #1 and #3

2022-11-18 00:53 UTC, jtyoung84 commented on .github/workflows/tag.yml
> +          custom_tag: ${{ steps.getversion.outputs.version }}
Add a new line to the file

2022-11-18 00:53 UTC, jtyoung84 requested changes
Add new line to end of file

2022-11-18 01:16 UTC, dana-rocha commented on .github/workflows/tag.yml
> +          custom_tag: ${{ steps.getversion.outputs.version }}
Just added!

2022-11-18 18:14 UTC, jtyoung84 approved these changes

2022-11-18 18:14 UTC, merged